

```{r}
install.packages("tidyverse")

library(tidyverse)
```

```{r}

capacity_pattern <- "(?<=\\d)(?=(?:\\s*\\d+\\s*(?:weeks|months|years)\\b))"

cc_details <- read_csv("distinct_details.csv")

cc_details_clean <- cc_details %>% 
  mutate(serious_injuries = as.character(serious_injuries)) %>% 
  mutate(fatalities = as.character(fatalities)) %>% 
  mutate(level = as.character(level))

for(row in 1:nrow(cc_details_clean)) {
  if (is.na(cc_details_clean$facility_name[row])) {
  }
  else if (str_detect(cc_details_clean$facility_name[row], "^[0-9]{5}")) {
    row_values <- cc_details_clean[row, ]
    shifted_values <- c(row_values[1], NA, row_values[-c(1, length(row_values))])
    cc_details_clean[row, ] <- shifted_values
  }
}

cc_details_standardized <- cc_details_clean %>% 
  mutate(fatalities = case_when(
    str_detect(fatalities, "none") ~ "0",
    TRUE ~ fatalities
  )) %>% 
  mutate(capacity = case_when(
    str_detect(capacity, "weeks") ~ gsub(capacity_pattern, " ", capacity, perl = TRUE)
  ))
  

```

