---
title: "Childcare Analysis"
author: "Khushboo Rathore"
date: "2024-07-03"
output: html_document
---

## Load libraries and establish settings

```{r}
# Turn off scientific notation
options(scipen=999)

# Load the tidyverse.
library(tidyverse)
library(lubridate)
library(dplyr)
library(janitor)
```

## Read facilities

```{r}
directory_current <- read_csv("LCC Directory.csv")

directory_clean <- directory_current %>% 
  clean_names() %>% 
  group_by(county) %>% 
  count()

directory_17 <- read_csv("LCC Directory 17.csv")

directory_17_clean <- directory_17 %>% 
  clean_names() %>% 
  group_by(county) %>% 
  count() %>% 
  rename(n_17 = n)

directory_20 <- read_csv("LCC Directory 20.csv")

directory_20_clean <- directory_20 %>% 
  clean_names() %>%
  group_by(county) %>% 
  count() %>% 
  rename(n_20 = n)

directory_23 <- read_csv("LCC Directory 23.csv")

directory_23_clean <- directory_23 %>% 
  clean_names() %>%
  group_by(county) %>% 
  count() %>% 
  rename(n_23 = n)

directory_dif <- directory_17_clean %>% 
  left_join(directory_20_clean) %>% 
  left_join(directory_23_clean) %>% 
  left_join(directory_clean) %>% 
  mutate(percent_dif_23 = (n-n_23)/n_23*100) %>% 
  mutate(percent_dif_20 = (n-n_20)/n_20*100) %>% 
  mutate(percent_dif_17 = (n-n_17)/n_17*100) 

write_csv(directory_dif, "year_difs.csv")
```